-- Custom types for roles and permissions
create type public.app_role as enum ('admin', 'publisher', 'user');
create type public.app_permission as enum (
    'books.create',
    'books.update',
    'books.delete',
    'books.read',
    'orders.create',
    'orders.read',
    'orders.update',
    'orders.delete',
    'users.manage',
    'publishers.manage'
);

-- Create user roles table
create table public.user_roles (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    role app_role not null default 'user',
    created_at timestamptz default now(),
    unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- Create role permissions table
create table public.role_permissions (
    id bigint generated by default as identity primary key,
    role app_role not null,
    permission app_permission not null,
    created_at timestamptz default now(),
    unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

-- Insert default role permissions
insert into public.role_permissions (role, permission)
values
    -- Admin permissions (all)
    ('admin', 'books.create'),
    ('admin', 'books.update'),
    ('admin', 'books.delete'),
    ('admin', 'books.read'),
    ('admin', 'orders.create'),
    ('admin', 'orders.read'),
    ('admin', 'orders.update'),
    ('admin', 'orders.delete'),
    ('admin', 'users.manage'),
    ('admin', 'publishers.manage'),
    
    -- Publisher permissions
    ('publisher', 'books.create'),
    ('publisher', 'books.update'),
    ('publisher', 'books.read'),
    ('publisher', 'orders.read'),
    
    -- User permissions
    ('user', 'books.read'),
    ('user', 'orders.create'),
    ('user', 'orders.read');

-- Create authorization function
create or replace function public.authorize(
    requested_permission app_permission
)
returns boolean as $$
declare
    bind_permissions int;
    user_role public.app_role;
begin
    -- Get user role from JWT
    select (auth.jwt() ->> 'user_role')::public.app_role into user_role;
    
    -- Count matching permissions
    select count(*)
    into bind_permissions
    from public.role_permissions
    where role_permissions.permission = requested_permission
        and role_permissions.role = user_role;
    
    return bind_permissions > 0;
end;
$$ language plpgsql security definer stable set search_path = public;

-- Create auth hook function
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
security definer
stable
as $$
declare
    claims jsonb;
    user_role public.app_role;
begin
    -- Get the user role
    select role into user_role 
    from public.user_roles 
    where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';
    
    if user_role is not null then
        claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else
        -- Default to 'user' role if none is set
        claims := jsonb_set(claims, '{user_role}', '"user"');
    end if;

    return jsonb_set(event, '{claims}', claims);
end;
$$;

-- Grant necessary permissions
grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
grant all on table public.user_roles to supabase_auth_admin;

-- Example RLS policies for books table
create policy "Allow read access to all users"
    on public.books
    for select
    using (true);

create policy "Allow publishers to create books"
    on public.books
    for insert
    to authenticated
    using ((SELECT authorize('books.create')));

create policy "Allow publishers to update their own books"
    on public.books
    for update
    to authenticated
    using ((SELECT authorize('books.update')) AND (publisher_id = auth.uid()));

create policy "Allow admin to delete books"
    on public.books
    for delete
    to authenticated
    using ((SELECT authorize('books.delete')));