// @ts-ignore .open-next/worker.js is generated by the OpenNext build
import handler from "./.open-next/worker.js";

async function expireAuthorApplications(env: any) {
  const db = env.DB as D1Database;
  if (!db) return;
  for (const statement of [
    "ALTER TABLE author_applications ADD COLUMN approved_at TEXT",
    "ALTER TABLE author_applications ADD COLUMN payment_deadline TEXT",
    "ALTER TABLE author_applications ADD COLUMN payment_order_id TEXT",
    "ALTER TABLE author_applications ADD COLUMN payment_id TEXT",
    "ALTER TABLE author_applications ADD COLUMN payment_currency TEXT",
    "ALTER TABLE author_applications ADD COLUMN payment_amount REAL"
  ]) { try { await db.prepare(statement).run(); } catch {} }

  const { results = [] } = await db.prepare(
    "SELECT id,full_name,email FROM author_applications WHERE status='approved_payment_pending' AND payment_deadline IS NOT NULL AND payment_deadline <= ?"
  ).bind(new Date().toISOString()).all<any>();

  const resendKey = String(env.RESEND_API_KEY || "");
  for (const application of results) {
    const updated = await db.prepare(
      "UPDATE author_applications SET status='expired',reviewed_at=? WHERE id=? AND status='approved_payment_pending'"
    ).bind(new Date().toISOString(), application.id).run();

    if (updated.success && resendKey) {
      try {
        const { Resend } = await import("resend");
        const resend = new Resend(resendKey);
        const safeName = String(application.full_name || "Author").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        await resend.emails.send({
          from: "no-reply@shoppersocean.com",
          to: application.email,
          subject: "Shoppers Ocean Author Registration",
          html: `<div style="font-family:Arial,sans-serif;line-height:1.7;color:#1e293b;">
            <p>Dear ${safeName},</p>
            <p>Sorry! Your author registration payment was not completed within the required 24-hour period. As a result, your registration as an author could not be completed.</p>
            <p>You may contact Shoppers Ocean if you wish to enquire about registering again.</p>
            <p>Regards,<br/>Shoppers Ocean</p>
          </div>`,
        });
      } catch (error) {
        console.error("Author expiry email failed:", error);
      }
    }
  }
}

export default {
  fetch: handler.fetch,
  async scheduled(_controller: ScheduledController, env: any, ctx: ExecutionContext) {
    ctx.waitUntil(expireAuthorApplications(env));
  },
};
