import type { CloudflareEnv } from "../auth/types";
export type OrderRow={id:string;user_id:string;product_id:string;quantity:number;total_amount:number;currency:string;status:string;contact_number:string|null;email:string|null;razorpay_order_id:string;order_date:string;created_at:string;updated_at:string;shipping_address:string|null;display_amount:number|null;display_currency:string|null};
export type PaymentRow={id:string;order_id:string;razorpay_order_id:string;payment_id:string;signature:string;status:string;original_currency:string|null;original_amount:number|null;amount_in_inr:number|null;payment_method:string|null;bank:string|null;card_network:string|null;card_last4:string|null;error_code:string|null;error_description:string|null;created_at:string;updated_at:string};
export async function getOrder(env:CloudflareEnv,id:string){return env.DB.prepare("SELECT * FROM orders WHERE id=?1 LIMIT 1").bind(id).first<OrderRow>();}
export async function getUserOrders(env:CloudflareEnv,userId:string){return env.DB.prepare("SELECT * FROM orders WHERE user_id=?1 ORDER BY order_date DESC").bind(userId).all<OrderRow>();}
export async function getOrderForBook(env:CloudflareEnv,userId:string,bookId:string){return env.DB.prepare("SELECT * FROM orders WHERE user_id=?1 AND product_id=?2 ORDER BY order_date DESC LIMIT 1").bind(userId,bookId).first<OrderRow>();}
export async function getPayment(env:CloudflareEnv,paymentId:string){return env.DB.prepare("SELECT * FROM payments WHERE payment_id=?1 LIMIT 1").bind(paymentId).first<PaymentRow>();}
export async function createOrderAndPayment(env:CloudflareEnv,order:Omit<OrderRow,"created_at"|"updated_at">,payment:Omit<PaymentRow,"created_at"|"updated_at">){
 await env.DB.batch([
  env.DB.prepare(`INSERT INTO orders (id,user_id,product_id,quantity,total_amount,currency,status,contact_number,email,razorpay_order_id,order_date,created_at,updated_at,shipping_address,display_amount,display_currency) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,datetime('now'),datetime('now'),?12,?13,?14)`).bind(order.id,order.user_id,order.product_id,order.quantity,order.total_amount,order.currency,order.status,order.contact_number,order.email,order.razorpay_order_id,order.order_date,order.shipping_address,order.display_amount,order.display_currency),
  env.DB.prepare(`INSERT INTO payments (id,order_id,razorpay_order_id,payment_id,signature,status,original_currency,original_amount,amount_in_inr,payment_method,bank,card_network,card_last4,error_code,error_description,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,datetime('now'),datetime('now'))`).bind(payment.id,order.id,payment.razorpay_order_id,payment.payment_id,payment.signature,payment.status,payment.original_currency,payment.original_amount,payment.amount_in_inr,payment.payment_method,payment.bank,payment.card_network,payment.card_last4,payment.error_code,payment.error_description)
 ]);
 return {order:await getOrder(env,order.id),payment:await getPayment(env,payment.payment_id)};
}
