/**
 * Server-side authentication utilities — Cloudflare D1 + JWT (Web Crypto API).
 */
export interface AuthUser { id:string; email:string; full_name:string|null; country:string|null; }
interface JWTPayload { sub:string; email:string; exp:number; iat:number; }
const enc=new TextEncoder(); const dec=new TextDecoder();
function b64e(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function b64d(value:string){let s=value.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return new Uint8Array([...atob(s)].map(c=>c.charCodeAt(0)))}
async function key(secret:string){return crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"])}
export async function createJwt(payload:Omit<JWTPayload,"iat"|"exp">,secret:string,expiresInSeconds=7*24*3600){if(!secret)throw new Error("JWT_SECRET is not configured");const now=Math.floor(Date.now()/1000);const full={...payload,iat:now,exp:now+expiresInSeconds};const h=b64e(enc.encode(JSON.stringify({alg:"HS256",typ:"JWT"})));const p=b64e(enc.encode(JSON.stringify(full)));const input=h+"."+p;const sig=new Uint8Array(await crypto.subtle.sign("HMAC",await key(secret),enc.encode(input)));return input+"."+b64e(sig)}
export async function verifyJwt(token:string,secret:string):Promise<JWTPayload|null>{if(!token||!secret)return null;try{const parts=token.split(".");if(parts.length!==3)return null;const [h,p,s]=parts;const input=h+"."+p;const valid=await crypto.subtle.verify("HMAC",await key(secret),b64d(s),enc.encode(input));if(!valid)return null;const payload=JSON.parse(dec.decode(b64d(p))) as JWTPayload;if(!payload.sub||!payload.email||payload.exp<=Math.floor(Date.now()/1000))return null;return payload}catch{return null}}
export async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));const material=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const hash=new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},material,256));return "pbkdf2$100000$"+b64e(salt)+"$"+b64e(hash)}
function equal(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0}
export async function verifyPassword(password:string,stored:string){const parts=stored.split("$");if(parts.length!==4||parts[0]!=="pbkdf2")return false;const iterations=Number(parts[1]);if(!Number.isInteger(iterations)||iterations<1)return false;try{const salt=b64d(parts[2]);const expected=b64d(parts[3]);const material=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const hash=new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations,hash:"SHA-256"},material,256));return equal(hash,expected)}catch{return false}}
const SESSION_COOKIE="so_session"; const SESSION_MAX_AGE=7*24*3600;
export function setSessionCookie(res:Response,token:string){res.headers.append("Set-Cookie",SESSION_COOKIE+"="+token+"; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age="+SESSION_MAX_AGE)}
export function clearSessionCookie(res:Response){res.headers.append("Set-Cookie",SESSION_COOKIE+"=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0")}
export function getSessionToken(req:Request){const match=(req.headers.get("cookie")||"").match(new RegExp(SESSION_COOKIE+"=([^;]+)"));return match?.[1]??null}
export async function getCurrentUser(req:Request,db:D1Database,jwtSecret:string):Promise<AuthUser|null>{const token=getSessionToken(req);if(!token)return null;const payload=await verifyJwt(token,jwtSecret);if(!payload)return null;return await db.prepare("SELECT id,email,full_name,country FROM users WHERE id=?").bind(payload.sub).first<AuthUser>()||null}
