/** Client-side authentication helpers for Cloudflare D1 + JWT cookie auth. */
export interface ClientUser { id:string; email:string; full_name:string|null; country:string|null; }
type AuthError={message:string;code?:string};
let cachedUser:ClientUser|null|undefined; let userPromise:Promise<ClientUser|null>|null=null;
async function readJson(res:Response){try{return await res.json()}catch{return {}}}
export function createClient(){return {auth:{
  async getUser():Promise<{data:{user:ClientUser|null};error?:AuthError}>{if(cachedUser!==undefined)return {data:{user:cachedUser}};if(!userPromise){userPromise=fetch("/api/auth/me",{credentials:"same-origin",cache:"no-store"}).then(async r=>{const data=await readJson(r);cachedUser=data?.user||null;return cachedUser}).catch(()=>{cachedUser=null;return null})}return {data:{user:await userPromise}}},
  async getSession(){if(cachedUser===undefined)await this.getUser();return cachedUser?{data:{session:{user:cachedUser,access_token:"cookie-auth"}}}:{data:{session:null}}},
  async signInWithPassword({email,password}:{email:string;password:string}):Promise<{data:{user:ClientUser|null};error:AuthError|null}>{try{const res=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",cache:"no-store",body:JSON.stringify({email,password})});const data=await readJson(res);if(!res.ok)return {data:{user:null},error:{message:data?.error||"Login failed",code:res.status===401?"invalid_credentials":undefined}};cachedUser=data?.user||null;userPromise=null;return {data:{user:cachedUser},error:null}}catch{return {data:{user:null},error:{message:"Unable to reach the sign-in service."}}}},
  async signUp({email,password,full_name,country}:{email:string;password:string;full_name?:string;country?:string}):Promise<{data:{user:ClientUser|null};error:AuthError|null}>{try{const res=await fetch("/api/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",cache:"no-store",body:JSON.stringify({email,password,full_name,country})});const data=await readJson(res);if(!res.ok)return {data:{user:null},error:{message:data?.error||"Signup failed"}};cachedUser=data?.user||null;userPromise=null;return {data:{user:cachedUser},error:null}}catch{return {data:{user:null},error:{message:"Unable to reach the sign-up service."}}}},
  async verifyOtp(_args:{phone:string;token:string;type:string}){return {error:new Error("Mobile verification is managed from Settings.")}},
  async signOut():Promise<{error:AuthError|null}>{try{const res=await fetch("/api/auth/logout",{method:"POST",credentials:"same-origin",cache:"no-store"});cachedUser=undefined;userPromise=null;return res.ok?{error:null}:{error:{message:"Unable to sign out."}}}catch{return {error:{message:"Unable to sign out."}}}}
}}}
