"use client";
import React,{useEffect,useState} from "react";
import {Input} from "@/components/ui/input"; import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Checkbox} from "@/components/ui/checkbox"; import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from "@/components/ui/alert-dialog";
import AddBookPopup from "./AddBookPopup"; import AdminSidebar from "../adminSidebar"; import {TooltipProvider} from "@/components/ui/tooltip"; import {Toaster} from "@/components/ui/toaster"; import {BookType} from "@/types/Books.type";
const cols:any[]=[["title","Title"],["description","Description"],["isbn","ISBN"],["pages","Pages"],["price","Price"],["ratings","Ratings"],["language","Language"],["genre","Genre"],["publisher","Publisher"],["author_name","Author"],["binding","Binding"],["published_date","Published Date"]];
export default function Books(){const[books,setBooks]=useState<BookType[]>([]),[filtered,setFiltered]=useState<BookType[]>([]),[showAdd,setShowAdd]=useState(false),[showEdit,setShowEdit]=useState(false),[showCols,setShowCols]=useState(false),[selected,setSelected]=useState<BookType|null>(null),[q,setQ]=useState(""),[del,setDel]=useState<BookType|null>(null),[selectedCols,setSelectedCols]=useState(new Set(["title","author_name","language"]));
const fetchBooks=async()=>{try{const r=await fetch("/api/admin/books",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setBooks(j.books||[])}catch(e){console.error(e)}};useEffect(()=>{fetchBooks()},[]);
useEffect(()=>{const s=q.toLowerCase().trim();setFiltered(s?books.filter((b:any)=>[b.title,b.author_name,b.language,b.publisher].some(v=>String(v||"").toLowerCase().includes(s))):[])},[q,books]);
const remove=async()=>{if(!del)return;const r=await fetch("/api/admin/books",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:del.id})});if(r.ok){setDel(null);fetchBooks()}};
const shown=filtered.length?filtered:books;
return <TooltipProvider><Toaster/><div className="flex h-screen bg-gray-100"><AdminSidebar/><main className="flex-1 overflow-y-auto p-8"><Card><CardHeader><CardTitle>Books Management</CardTitle></CardHeader><CardContent><div className="flex justify-between mb-4"><div className="space-x-2"><Button className="bg-blue-600 text-white" onClick={()=>setShowAdd(true)}>Add New Book</Button><Button className="bg-blue-600 text-white" onClick={()=>setShowCols(true)}>Columns to Display</Button></div></div><Input placeholder="Search by title, author, language, or publisher" value={q} onChange={e=>setQ(e.target.value)} className="mb-4"/><Table><TableHeader><TableRow>{Array.from(selectedCols).map((c:any)=><TableHead key={c}>{cols.find(x=>x[0]===c)?.[1]}</TableHead>)}<TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{shown.map((b:any)=><TableRow key={b.id}>{Array.from(selectedCols).map((c:any)=><TableCell key={c}>{c==="author_name"?(b.authors?.name||b.author_name||""):String(b[c]??"")}</TableCell>)}<TableCell><Button className="bg-blue-600 text-white mr-2" onClick={()=>{setSelected(b);setShowEdit(true)}}>Edit</Button><Button variant="destructive" onClick={()=>setDel(b)}>Delete</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
<Dialog open={showAdd} onOpenChange={setShowAdd}><DialogContent className="max-h-[80vh] overflow-y-auto"><DialogHeader><DialogTitle>Add New Book</DialogTitle></DialogHeader><AddBookPopup onSuccess={()=>{setShowAdd(false);fetchBooks()}}/></DialogContent></Dialog>
<Dialog open={showEdit} onOpenChange={setShowEdit}><DialogContent className="max-h-[80vh] overflow-y-auto"><DialogHeader><DialogTitle>Edit Book</DialogTitle></DialogHeader>{selected&&<AddBookPopup book={selected} onSuccess={()=>{setShowEdit(false);fetchBooks()}}/>}</DialogContent></Dialog>
<Dialog open={showCols} onOpenChange={setShowCols}><DialogContent><DialogHeader><DialogTitle>Select Columns</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-4">{cols.map(([key,label])=><label key={key} className="flex items-center gap-2"><Checkbox checked={selectedCols.has(key)} onCheckedChange={(v)=>{const n=new Set(selectedCols);v?n.add(key):n.delete(key);setSelectedCols(n)}}/>{label}</label>)}</div></DialogContent></Dialog>
<AlertDialog open={!!del} onOpenChange={v=>!v&&setDel(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirm Deletion</AlertDialogTitle><AlertDialogDescription>Are you sure you want to delete "{del?.title}"?</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={remove}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</main></div></TooltipProvider>}
